name: Build and Deploy

# å½“æœ‰æ–°pushæˆ–è€…præ—¶è¿è¡Œ
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ä¸€é¡¹å«åšbuild-and-deployçš„ä»»åŠ¡
  build-and-deploy:
    # åœ¨æœ€æ–°ç‰ˆçš„Ubuntuç³»ç»Ÿä¸‹è¿è¡Œ
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # æ¥è‡ªå®˜æ–¹è„šæœ¬ï¼šhttps://github.com/marketplace/actions/checkout

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3 # è„šæœ¬æ¥è‡ªï¼š https://github.com/JamesIves/github-pages-deploy-action
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
