name: Build and Deploy

# å½“æœ‰æ–°pushæˆ–è€…præ—¶è¿è¡Œ
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ä¸€é¡¹å«åšbuild-and-deployçš„ä»»åŠ¡
  build-and-deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # åœ¨æœ€æ–°ç‰ˆçš„Ubuntuç³»ç»Ÿä¸‹è¿è¡Œ
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # æ¥è‡ªå®˜æ–¹è„šæœ¬ï¼šhttps://github.com/marketplace/actions/checkout
        with:
          node-version: 18.16.0
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3 # è„šæœ¬æ¥è‡ªï¼š https://github.com/JamesIves/github-pages-deploy-action
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: build
          path: dist/
